version: '3.8'

services:
  postgres:
    image: postgres
    container_name: some-postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge