@maten_backend_HostAddress = http://localhost:5184

GET {{maten_backend_HostAddress}}/recipes/
Accept: application/json

###

DELETE {{maten_backend_HostAddress}}/recipes?id=01945ab0-5bf8-7b75-a35e-5a9ad5eab440
Accept: application/json

###

POST {{maten_backend_HostAddress}}/recipes?name=lasagne
Content-Type: application/json
{
  "name": "Pasta Carbonara",
  "instructions": [
    {
      "StepNumber": 1,
      "Text": "Boil water"
    },
    {
      "StepNumber": 2,
      "Text": "Cook pasta"
    }
  ]
}

###